### ISSUE TITLE
SSH authentication errors during kitchen converge, but works fine with ssh directly

### ISSUE THREAD

**Issue by thercast** [test-kitchen/kitchen-digitalocean#43]
Hi, I'm fairly new to using kitchen for my chef cookbooks but I use Digital Ocean for a lot of my infrastructure, so having this plugin available is a great option.  I'm using a centos 6.5 DO droplet as my workstation and I installed chef-dk along with this plugin (version 0.9.2).  Within a simple cookbook I've set up my `.kitchen.yml` as below:

```
---
driver:
  name: digitalocean

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5
    driver_config:
      region: nyc3
      size: 1gb
      ssh_key_ids: '11111'

suites:
  - name: default
    run_list:
      - recipe[localswap]
    attributes:
```

I actually have three ssh keys on my DO account, but for simiplicity I decided to use one key that is directly on my workstation (also a DO droplet).  The droplet creation itself seems to work fine, but it has a few failed attempts to authenticate via SSH and finally just prompts me for the root user password, which is not defined anywhere.  Here's the log output after using the debug flag (I've anonymized my API key):

```
[eric@docker-centos swap]$ kitchen converge default-centos-65 -l debug
-----> Starting Kitchen (v1.4.0)
-----> Creating <default-centos-65>...
D      digitalocean:name defaultcentos65-eric-dockercentos-3sbystb
D      digitalocean:imagecentos-6-5-x64
D      digitalocean:size 1gb
D      digitalocean:region nyc3
D      digitalocean:ssh_key_ids 987585
D      digitalocean:private_networking true
D      digitalocean:ipv6 false
D      digitalocean_api_key <api_key>
       Digital Ocean instance <6309796> created.
D      digitalocean_api_key <api_key>
D      digitalocean_api_key <api_key>
D      [SSH] opening connection to root@45.55.80.56<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>"22", :compression=>"zlib", :compression_level=>6, :keepalive=>true, :keepalive_interval=>60, :timeout=>15}>
D      [SSH] connection failed (#<Timeout::Error: execution expired>)
       Waiting for SSH service on 45.55.80.56:22, retrying in 3 seconds
D      [SSH] opening connection to root@45.55.80.56<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>"22", :compression=>"zlib", :compression_level=>6, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :user=>"root"}>
D      [SSH] connection failed (#<Timeout::Error: execution expired>)
       Waiting for SSH service on 45.55.80.56:22, retrying in 3 seconds
D      [SSH] opening connection to root@45.55.80.56<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>"22", :compression=>"zlib", :compression_level=>6, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :user=>"root"}>
D      [SSH] connection failed (#<Timeout::Error: execution expired>)
       Waiting for SSH service on 45.55.80.56:22, retrying in 3 seconds
D      [SSH] opening connection to root@45.55.80.56<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>"22", :compression=>"zlib", :compression_level=>6, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :user=>"root"}>
D      [SSH] connection failed (#<Errno::ECONNREFUSED: Connection refused - connect(2) for "45.55.80.56" port 22>)
       Waiting for SSH service on 45.55.80.56:22, retrying in 3 seconds
D      [SSH] opening connection to root@45.55.80.56<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>"22", :compression=>"zlib", :compression_level=>6, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :user=>"root"}>
root@45.55.80.56's password:
```

I am able to connect to the machine directly with the ssh key matching the numeric ID in `.kitchen.yml` via `ssh -i ~/.ssh/id_rsa root@45.55.80.56` and have it authenticate correctly. Within this new server I see that the same key is properly added to `~/.ssh/authorized_keys`.  Am I missing another parameter I need to set in the configuration or command line to make this work?

**Comment by thercast** [comment]
Just checking to see if anyone had an idea of how to solve this issue?  Please let me know if you'd like some additional diagnostic information.

**Comment by gregf** [comment]
@thercast I never got a email notification for this bug, sorry for the long wait. I will try to reproduce and fix this sometime tonight.

**Comment by gregf** [comment]
@thercast  I decided to take a break and take a quick look at this. I wasn't able to reproduce it. Are you running this on windows or linux?

Can you make sure you have the latest test-kitchen and kitchen-digitalocean installed and try again?

You may also want to try deleting your key for digitalocean and adding it again, maybe theres a formatting issue with your key?

Just a few thoughts.

**Comment by thercast** [comment]
Hi @gregf, thanks for getting back to me.  I've upgraded kitchen-digitalocean to the latest version with `gem install --upgrade kitchen-digitalocean` and I'm still getting the same login problem.  I'm using a CentOS 7 workstation (also deployed on Digital Ocean) as my workstation, with Chef-DK installed (using kitchen `1.4.0`).  Here are some additional observations:

* I also use the [knife-digital-ocean](https://github.com/rmoriz/knife-digital_ocean) plugin to create droplets to test my Chef recipes, and there are no problems when using the same ssh keys and access token as I do here.  
* The droplet itself is created when I run `kitchen_converge` but after a few connection tries I'm requested to enter the root password for the droplet.  At that point I just kill the process, but the new droplet itself is still intact.
* In another terminal on the same workstation I connect to the newly-created droplet using one of the SSH keys that is specified in the `DIGITALOCEAN_SSH_KEY_IDS` environment variable.  I add an entry in my `~/.ssh/config` file for the new droplet so I can specify the ssh key directly.  Then I'm able to connect without being prompted for my password, and I can see all of the keys from `DIGITALOCEAN_SSH_KEY_IDS` listed in the droplet's `/root/.ssh/authorized_keys` file.  

Another note is that the primary key I've been using in this workstation to bootstrap has a custom name `~/.ssh/id_rsa_lux` and `~/.ssh/id_rsa_lux.pub`.  Since it is not named `id_rsa` do you think that's causing the issue?  When I have a chance I'll try creating a new client that uses a different distribution like Ubuntu to see if the same problem occurs.

**Comment by gregf** [comment]
@thercast This appears to be a bug in the `droplet_kit` gem we are using. If the key is named id_rsa or id_dsa it works fine. So if you could rename your key to one of those it will work for the time being. I'm opening a bug report upstream that you can follow [here](https://github.com/digitalocean/droplet_kit/issues/66)

**Comment by gregf** [comment]
@thercast turns out this is just a test-kitchen option. You need to do something like this in  your .kitchen.yml

```
driver_config:
  ssh_key: ~/.ssh/id_rsa.digitalocean
```

It should then work. If not please run test kitchen with --log-level=debug and send me the output.

**Comment by thercast** [comment]
Hi @gregf, I was able to get it to work but for some reason I have to use the fully qualified path to my SSH key in the config option:

```
driver:
  name: digitalocean
  private_networking: false
  ssh_key: /home/eric/.ssh/id_rsa_lux
```

When I tried using `~/.ssh/id_rsa_lux` as the path I got an error saying the key file was not found.  Anyway I'm happy that now I can use this plugin as intended.  Thanks for helping me solve this annoying issue!

**Comment by gregf** [comment]
@thercast expand_path was added to ssh_key in test-kitchen 1.4.0 so make sure your up to date if you want to use ~.

**Comment by skiwheelr** [comment]
I am having the same issue no matter what path I try.
I see there is a dummy_vaidation.pem file somewhere in there. 
Should I replace dummy with mine (called regional.pem) 
<img width="805" alt="screen shot 2018-05-16 at 4 38 48 pm" src="https://user-images.githubusercontent.com/16263861/40145893-32c35f02-5929-11e8-991b-9fdfd202e203.png">
<img width="728" alt="screen shot 2018-05-16 at 4 45 42 pm" src="https://user-images.githubusercontent.com/16263861/40145894-32da559a-5929-11e8-819e-8cf105f23dc8.png">
