### ISSUE TITLE
InSpec test fail when using DigitalOcean plugin

### ISSUE THREAD

**Issue by onlyhavecans** [test-kitchen/kitchen-digitalocean#49]
Failed to complete #verify action: [Client error, can't connect to 'ssh' backend: You must configure at least one authentication method for SSH: Password or key.] on default-ubuntu-1404

it seems the DigitalOcean driver needs to be upgraded to the newer test kitchen APIs

https://github.com/test-kitchen/test-kitchen/blob/30597fc30cbbf40efb8539c512af399157da3809/lib/kitchen/instance.rb#L598-L610

It's hitting that which is calling an older setup method that Inspec cannot use as a verification method

Full detail

```
[36m       Finished converging <default-ubuntu-1404> (2m11.16s).[0m
[36m-----> Setting up <default-ubuntu-1404>...[0m
[36m$$$$$$ Running legacy setup for 'Digitalocean' Driver[0m
[36m       Finished setting up <default-ubuntu-1404> (0m0.00s).[0m
[36m-----> Verifying <default-ubuntu-1404>...[0m
[36m-----> Destroying <default-ubuntu-1404>...[0m
[36m       Digital Ocean instance <27328542> destroyed.[0m
[36m       Finished destroying <default-ubuntu-1404> (0m0.74s).[0m
[31m>>>>>> ------Exception-------[0m
[31m>>>>>> Class: Kitchen::ActionFailed[0m
[31m>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #verify action: [Client error, can't connect to 'ssh' backend: You must configure at least one authentication method for SSH: Password or key.] on default-ubuntu-1404[0m
[31m>>>>>> ----------------------[0m
[31m>>>>>> Please see .kitchen/logs/kitchen.log for more details[0m
[31m>>>>>> Also try running `kitchen diagnose --all` for configuration
[0m
rake aborted!
Command failed with status (20): [kitchen test --destroy=always default...]
/home/travis/build/dnsimple/dnsimple-nginx-cookbook/Rakefile:45:in `block (2 levels) in <top (required)>'
Tasks: TOP => travis => cloud:travis
(See full trace by running task with --trace)
```

**Comment by gregf** [comment]
Happy to take a PR on this if you got the time

**Comment by gregf** [comment]
I'll be looking into this soon myself, as I plan to switch to inspec on my tests. Keep you posted on what I find out.

**Comment by gregf** [comment]
Now I look at this, it looks like an issue in your rake file. I'm not having this issue, I just wrote some inspec tests and they ran fine. 

I'm going to close this, but if it's still an issue please reopen with a link to a public repo that fails to run and I'll take a look.
