### ISSUE TITLE
File transfer is extremely slow

### ISSUE THREAD

**Issue by fabn** [test-kitchen/kitchen-digitalocean#51]
I configured my CI environment to run with this driver to avoid vagrant and virtualbox, everything works, however file transfer is extremely slow.

While executing it remains on this lines for minutes to move a kitchen with about 12MB of data.

```
       Installing chef
       installing with dpkg...
       Selecting previously unselected package chef.
(Reading database ... 61455 files and directories currently installed.)
       Preparing to unpack .../chef_12.19.36-1_amd64.deb ...
       Unpacking chef (12.19.36-1) ...
       Setting up chef (12.19.36-1) ...
       Thank you for installing Chef!
       Transferring files to <default-ubuntu-1404>
```

Vagrant driver doesn't have this issue so I assume it might be related to this gem.

Any hint?

**Comment by gregf** [comment]
This isn't a driver specific issue. This is more of a test-kitchen issue, why don't you open an issue over [there](https://github.com/test-kitchen/test-kitchen/issues/new)
