### ISSUE TITLE
Looking for new maintainer

### ISSUE THREAD

**Issue by gregf** [test-kitchen/kitchen-digitalocean#54]
I'm looking for someone to step up and take this plugin over. I no longer use chef or digitalocean at this point in my life. 

@sethvargo  I know you no longer work for chef, but can you help in this process since you brought me onto the project? I would like to see it go to a good home.

**EDIT** I would be more than happy to mentor someone if any needs help getting started.

**Comment by martinisoft** [comment]
If Chef would want to take control of this project we can ping @cheeseplus and he/Chef could find additional maintainers while he takes over.

**Comment by cheeseplus** [comment]
I already have org owner perms for everything under `test-kitchen/` on GitHub so the only thing we'd need to get started is getting at least myself added as a gem owner (sthomas@chef.io or cheeeplus on RubyGems). That will unblock us publishing new versions and I can nominally own it (in so much as I own many of the tk plugins) until such a time as someone would like to join/take over maintenance.

Thanks for the the response @gregf and even more thanks for being a maintainer.

**Comment by gregf** [comment]
@cheeseplus 

```
gem owner kitchen-digitalocean -a sthomas@chef.io
Owner added successfully.
Owners for gem: kitchen-digitalocean
- sthomas@chef.io
- greg@gregf.org
```

**Comment by gregf** [comment]
Small update here, I changed jobs again and I'm back to doing chef stuff. This means I'll be able to continue maintaining this now. I'll be doing some work on it later today. If there's any feature requests people have, please open an issue.
