### ISSUE TITLE
can I get the public IP of one node?

### ISSUE THREAD

**Issue by caarlos0** [test-kitchen/kitchen-digitalocean#63]
for a test case here, I need to create 4 nodes, and all nodes must know the IP of the other nodes...

Is there a way I can get ip of the created nodes in the `attributes` section?

**Comment by gregf** [comment]
That's a good question, i'm not sure. Maybe create an issue on test-kitchen itself.

**Comment by gregf** [comment]
I'm not sure how you want this exposed but its now in the debug info.
