### ISSUE TITLE
I am having the same issue no matter what path I try.

### ISSUE THREAD

**Issue by Roopeshvarmanampally** [test-kitchen/kitchen-digitalocean#80]
I am having the same issue no matter what path I try.
I see there is a dummy_vaidation.pem file somewhere in there. 
Should I replace dummy with mine (called regional.pem) 
<img width="805" alt="screen shot 2018-05-16 at 4 38 48 pm" src="https://user-images.githubusercontent.com/16263861/40145893-32c35f02-5929-11e8-991b-9fdfd202e203.png">
<img width="728" alt="screen shot 2018-05-16 at 4 45 42 pm" src="https://user-images.githubusercontent.com/16263861/40145894-32da559a-5929-11e8-819e-8cf105f23dc8.png">

_Originally posted by @skiwheelr in https://github.com/test-kitchen/kitchen-digitalocean/issues/43#issuecomment-389677160_

**Comment by gregf** [comment]
That pem file is from berkshelf. You should speak with them probably. I'm not sure off the top of my head. I have never ran into this.

**Comment by gregf** [comment]
Second look it says ssh connection refused, make sure your ssh credentials to localhost is right. Can you post your .kitchen.yml?
