### ISSUE TITLE
Moving On

### ISSUE THREAD

**Issue by ghost** [test-kitchen/kitchen-digitalocean#88]
I haven't really been using this driver for the last year or more. I'm burnt out on open source and want to hand this over to someone else that cares about it.

I'll also be removing my GitHub account, I have moved onto a private GitLab instance 2 years ago and don't really use GitHub.

I will give this a few weeks for someone to step up then, I'm just removing my GitHub account. 

So long, and thanks for all the fish.

@tas50 Sorry to do this, hoping you might want to take this over you have done most of the work recently anyways.

**Comment by tas50** [comment]
@gregf It's been great to have your help all these years. Thanks for everything

**Comment by gregf** [comment]
@tas50 I believe you or someone at chef has gem push rights? I can make whoever needs it the new maintainer there as well. Just need to know who wants to take this over.

Digitalocean was giving credits to me for testing the driver. I no longer have a contact I haven't requested any in a while, but if someone were to reach out to them, they might be willing to help whoever takes it over with some credits.
